version: '3.8'

services:
  map-web:
    image: nginx:alpine
    container_name: map_phuquoc_web
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html
    restart: unless-stopped